### ISSUE TITLE
Status attributes in `defstyled`

### ISSUE THREAD

**Issue by roman01la** [roman01la/cljss#20]
I've seen this idea popping out in a couple of CSS-in-JS libraries. Basically this is an additional syntax to allow declarative states definition

Instead of this
```clojure
(defstyled Menu :menu
  {:width (with-meta #(if % "16px" "240px") :hidden?)})

(Menu {:hidden? true})
```

Do this
```clojure
(defstyled Menu :menu
  {:width "240px"
   :hidden? {:width "16px"}})

(Menu {:hidden? true})
```

thoughts? @brianium

**Comment by roman01la** [comment]
pushed initial implementation https://github.com/roman01la/cljss/commit/62366f97cfae5df69b93cd40d1226c516c699ce3

**Comment by brianium** [comment]
@roman01la you're killing it! 💯  

If it's helpful, I will take a look at this along with #17 tomorrow morning.

Thank you!

**Comment by brianium** [comment]
Is the pattern a little loose on this [line](https://github.com/roman01la/cljss/commit/62366f97cfae5df69b93cd40d1226c516c699ce3#diff-88ff2d577c24331f96863b5483beec8aR17)?

I think it is currently working in the example because of the `map?` check - but I think instead of the pattern `#"^.*\??"` - you would want something that doesn't make the `?` optional correct? Something closer to `#"^.*\?$"`? The current pattern would match `:hidden` and `:hidden?`

**Comment by roman01la** [comment]
@brianium oh crap! you are right

**Comment by roman01la** [comment]
fixed

**Comment by brianium** [comment]
The rest of the code looks good - haven't tested it, but I should be able to do that tonight or tomorrow as well.

If it's helpful - you can submit pull requests and we can leverage the review tools in GitHub. I would totally be willing to do that. Whatever works best for you.

**Comment by brianium** [comment]
@roman01la didn't get around to actually pulling this into an app this morning - but I will definitely be able to do so tonight 👍

**Comment by brianium** [comment]
@roman01la - had to rebase against master to try within my project, but everything seems to be working. Anything else I can do to help out with this?

**Comment by roman01la** [comment]
Thanks! Going to release this.
